# Site settings
name: St Mark's New Ferry
navigation_pages:
- about
- whats-on
- contact
collections:
- home_boxes
- about_boxes
- team_members
- whats_on_boxes
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
