# Site settings
name: St Mark's New Ferry
source: ./contents
layouts: ./_layouts
collections:
- team
- whats_on
- home_boxes
- about_boxes

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
