# Site settings
name: St Mark's New Ferry
collections:
- home_boxes
- about_boxes
- team_members
- whats_on_boxes

# Build settings
markdown: kramdown
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
