# Site settings
name: St Mark's New Ferry
navigation_pages:
- about
- whats-on
- contact
collections:
- home_boxes
- about_boxes
- team_members
- whats_on_boxes
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME

# GitHub settings https://help.github.com/articles/using-jekyll-with-pages/

# Configurable
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems: []
  # - jekyll-coffeescript
  # - jekyll-paginate

# Settings that cannot be changed
lsi: false
# safe: true # <-- activating this seems to disable jekyll-paginate!
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
